.gitignore
github.sh

- fixes https://github.com/tvpeter/yt2btc/issues/8#issue-1516687563
- fixes https://github.com/tvpeter/yt2btc/issues/7#issue-1516685788

Fix recloning

---

Readme.md
app/application.py
yttbtc.py

- remove cli flags
- update readme
- fixes https://github.com/tvpeter/yt2btc/issues/4#issue-1516678172
- add model flag for transcription
- fixes https://github.com/tvpeter/yt2btc/issues/11#issue-1520993280

remove flags for cli arguments in transcription command

---

app/application.py
github.sh
yttbtc.py

- refactor writing transcribed text to files
- add creating _index.md files in new directories and sub-directories
- resolves https://github.com/tvpeter/yt2btc/issues/20#issue-1522837625

Add creating _index.md in new directories

---

app/application.py
transcriber.py

Added speakers, categories and tags options to the cli

feat: added new options to the CLI

---

transcriber.py

fix: fixed the version flag

---

Readme.md
app/application.py
requirements.txt
transcriber.py

feat: added support for audio files

---

app/application.py
github.sh
initializeRepo.sh
transcriber.py

feat: added support for youtube chapters

---

transcriber.py

fix: leading slash for file paths

---

app/application.py

fix: no empty strings in front matter

---

github.sh
transcriber.py

feat: update the auto commit messages

---

.gitignore
app/application.py
transcriber.py

feat: added username remember support

---

app/application.py
github.sh
transcriber.py

chore: fixed the transcript_by

---

Readme.md

@masterchief164 & @adamjonas,
I'm submitting some updates to the ReadMe for consideration. The goal is to help new users understand how to use the tool and what the arguments mean.
I see there is an open issue for updating the ReadMe (#63). Hopefully, this helps with that, though this doesn't cover everything. I'm still learning the code base, so I didn't want to elaborate on chapter extraction, local file support, etc. until I get a better understanding of how that's working under the hood.

add info on tool arguments and add an example

---

.github/workflows/python-package.yml

This PR fixes #67. This tests all the tests marked as `feature` and runs them quietly.

test: added github workflow

---

.gitignore
Readme.md
app/application.py
test/test_cli.py
transcriber.py

feat: added support for https links

---

Readme.md
app/application.py
test/test_audio.py
test/test_cli.py
test/test_video.py

feat: added support for local files

---

Readme.md

fixup README

---

app/application.py
transcriber.py

fix: added more descriptive error messages

---

app/application.py

feat: added dates from the video meta data

---

app/application.py
test/test_cli.py

feat: tmp files stored in tmp folder

---

app/application.py
transcriber.py

fix: error in event_date

---

Readme.md

feat: updated the readme

---

app/application.py
requirements.txt
transcriber.py

feat: added support for large whisper model

---

app/application.py
test/test_audio.py
test/test_cli.py
test/test_video.py
transcriber.py

This PR concerns the management of temporarily generated files using `tempfile` module. Previously, manual ad-hoc directory management was being used.
This PR works on top of:
- #105
-  #108

[Refactor] Use `tempfile`

---

.gitignore
Readme.md
app/application.py
requirements.txt
test/test_cli.py
transcriber.py

This PR works on top of:
- #105 
- #108 
- #109
- #110

[Feature] Upload model outputs to Amazon S3 Bucket

---

Readme.md
app/application.py
requirements.txt
test/test_cli.py
transcriber.py

These fixes are some minor issues (and enhancements) that I stumbled upon while trying to run the setup locally. You can find more information about each fix at the respective commit.

Minor misc fixes

---

README.md
app/media_processor.py
requirements.txt
server.py

This PR adds support for FastAPI.
This PR adds an endpoint with new functionality that is needed for https://github.com/bitcointranscripts/transcription-review-front-end/pull/297.
The plan is to slowly refactor tstbtc to a server with which the CLI tool will interact through the API interface.

Add support for FastAPI
